### ISSUE TITLE
Clock Fades off always

### ISSUE THREAD

**Issue by imCharlieB** [florianL21/LED-ClockShelf#14]
I cant seem to get this to work i have tried tons of setting for the light sensor and nothing will keep the clock on it comes up goes thru animation then shows clock then fades away even does this if i turn off the light sensor any ideas? 
i can watch the reading of the light sensor in the serial and i dont see anything change to make it fade off  seems lower number brightness makes it brighter and higher is less i have changed ranges i had it at 194 for 10 min then changed some settings and had it at 25 and both do the same

**Comment by florianL21** [comment]
Am I guassing correctly that you are not using Blynk to control the clock?
If that is the case then this might be an issue with the defaults that I set. Could you try to remove this if/else statement and only leave in the part from the if part and see if it fixes your issue? 

https://github.com/florianL21/LED-ClockShelf/blob/ddbdf48fbfc5200c0e5b12c3f037c464712027fe/lib/LED_clock/Modules/ClockState/src/ClockState.cpp#L59

**Comment by imCharlieB** [comment]
I had to remove both if and else to get it to work but its working now..

and correct no blynk

**Comment by florianL21** [comment]
Okay then this is an oversight from my side. I'll need to set reasonable defaults for the night time when blynk is deactivated

**Comment by imCharlieB** [comment]
i also had to move this line 
BlynkConfig* BlynkConfiguration = BlynkConfig::getInstance();
in the main i moved it up into the if is_blynk_active

it would fail to compile with blynk turned off

**Comment by florianL21** [comment]
If you find the time, would you mind confirming that with these changes this bug is indeed fixed?
https://github.com/florianL21/LED-ClockShelf/tree/blynk-update

**Comment by florianL21** [comment]
Closing this issue since a fix should be in place and there are no further complaints
