### ISSUE TITLE
File corrupted since updated code

### ISSUE THREAD

**Issue by Cayn183** [florianL21/LED-ClockShelf#19]
Hello Florian,

I am currently using my clock with the old code for over a year and I am very happy with it.
Unfortunately, due to the recent shutdown of the old Blynk servers, I was forced to update the clock to the new version.
I made the adjustments as with the old code and also tried various other variants to get the clock running. However, it keeps restarting itself. A file appears to be corrupt in the serial log.
Could you please help me to find the error?

Best regards
Aaron

```
--- Terminal on COM5 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time                                                                                       
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
..Reconnect successful
Waiting for loading animation to finish...
OTA update functionality is ready
IP address: 192.168.178.96
[3205]
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v1.2.0 on ESP32

 #StandWithUkraine    https://bit.ly/swua


Starting blynk on core 0...
Fetching time from NTP server...
Loop task running on core 0
[3227] Connecting to blynk.cloud:80
[3294] Ready (ping: 13ms).
Displaying startup animation...
Setup done. Main Loop starting...

abort() was called at PC 0x4008500f on core 1


Backtrace:0x40083b29:0x3ffbeedc |<-CORRUPTED




ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
..Reconnect successful
Waiting for loading animation to finish...
OTA update functionality is ready
 #StandWithUkraine    https://bit.ly/swua


Starting blynk on core 0...
Fetching time from NTP server...
Loop task running on core 0
[3229] Connecting to blynk.cloud:80
Displaying startup animation...
[3288] Ready (ping: 14ms).
Setup done. Main Loop starting...

```

**Comment by florianL21** [comment]
Can you let me know what files you changed? 
Probably only the Configuration.h I am suspecting. Did you change anything apart from the WIFI SSID/PW and your blynk credentials?

**Comment by Cayn183** [comment]
I have changed a few things, i test it with a unchanged version only wifi, disabled blynk.
Before change, I have used a modified diy-mashines with 24h and disabled 0 in the hour but not in the minute.

**Comment by florianL21** [comment]
Could you please create a fork of the repository and commit your changed files? That way we will have a good diff and I would then be able to help and reproduce a potential bug on my side

**Comment by Cayn183** [comment]
I have tested it with the blank code.
After ~15min i have got the corrupted file again in the terminal.
Make it a change if i upload the code per serial? i actually load it via the ota updater?

**Comment by florianL21** [comment]
I have not had any reports of this happening so far, and the new version has been out since quite some time now. 
It should not make a difference if you upload it via OTA or serial. If you are saying it happens without any changes, I assume that that means also without providing any WiFi or timezone information?

**Comment by Cayn183** [comment]
I have only disabled blynk for the test and have put wifi credentials. 
Also i have uploaded the blank without any changes. But i have found that it reboots after 30mins, thats the sinc time of the clock. When i edit it to 5mins, i get the problem every 5 mins.

**Comment by florianL21** [comment]
You are right, I was also able to reproduce your issue now. *Something* seems to have changed since I developed it.
I was able to find a fix, I think. It should already be on the master branch. Just pull and retry it and then let me know if you ran into any more issues
