### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by masterbalby2** [florianL21/LED-ClockShelf#21]
After several weeks of work I finally finished making the shelf.
The leds are installed and the printed covers are in place.
I programmed my esp32 and wired it to the leds through a 74AHCT125N levelshifter.
Everything works fine but after a few minutes (between 5 and 10 minutes) the system freezes.
I don't understand what causes this freeze.
Do you have any ideas?
PS: thank you for this great project

**Comment by florianL21** [comment]
There was a bug in the code that would cause system resets a few weeks ago. Did you use the newest version of the code?
If you are still having issues try to disable Blynk as a first step to see if it is still happening

**Comment by masterbalby2** [comment]
Ok thanks for the answer. 
I am using the latest version of the code.
I'll try tonight by disabling Blynk.

**Comment by masterbalby2** [comment]
The problem seems to be solved.
Indeed I did not have the last version of the code.
With the last one everything works and no more freeze of the clock with blink activated.
Thanks

**Comment by florianL21** [comment]
Great to hear :)
