### ISSUE TITLE
Segment error when uplaoding

### ISSUE THREAD

**Issue by Godzookee** [florianL21/LED-ClockShelf#22]
Hi there,

Appreciate all the work you have done here.  Hoping you might be able to assist me.  I created the DIY machines version of the setup and want to swap to the esp32 so my LED's are wired as per the DIY machines walkthrough.  Am I correct the if the use the DIY_machines.json file it will take this into account?

If this is so I have tried this and unfortunately receive the following errors

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
[W] Segment not valid; Position: 4; Display: 3
[W] Segment not valid; Position: 0; Display: 3
[W] Segment not valid; Position: 1; Display: 3
[W] Segment not valid; Position: 5; Display: 3
[W] Segment not valid; Position: 4; Display: 3
[W] Segment not valid; Position: 4; Display: 3
[W] Segment not valid; Position: 0; Display: 3
[W] Segment not valid; Position: 0; Display: 3
[W] Segment not valid; Position: 1; Display: 3
[W] Segment not valid; Position: 1; Display: 3
[W] Segment not valid; Position: 5; Display: 3
[W] Segment not valid; Position: 5; Display: 3
[E] Complex animtation start point was empty. Animation step (0) was not started.
.E (662) wifi:Association refused temporarily, comeback time 1048 mSec
.....Reconnect successful
Waiting for loading animation to finish...
OTA update functionality is ready
IP address: 192.168.XXX.XXX
Fetching time from NTP server...
Displaying startup animation...
Setup done. Main Loop starting...

If I upload the 12h-extended version for testing it uploads and shows no errors.

Any assistance is appreciated.  Please let me know if I need to provide further information.

Many Thanks

**Comment by florianL21** [comment]
That was a very good catch. This should not actually have caused any issues, but it would have prevented the startup animation from showing on the display. 
I moved the animation to the lower digit minute display. Before it tried to run it on the highest digit display which in this configuration is ofc missing segments. 

If you cloned this with git, please run a "git pull", recompile it and let me know if it is now showing a proper startup animation (should be running a loop around the lower digit minute segment while it is trying to regain the wifi connection) because I do not have the diy machines wired version of the display and can thus not test it.

**Comment by Godzookee** [comment]
Perfect. Thank you so much.

The clock now displays the time. it fades on and off once.  Is this normal behavior or have I missed a setting some where?

So many thanks I have been working on this project on an off for a number of years now and the is the biggest breakthrough for me in a long time.

Cheers

**Comment by florianL21** [comment]
The fading might have something to do with the default brightness, the brightness setting from Blynk if you use it, the light sensor if you use it and the night mode settings. But honestly if it does it only once during startup I wouldn't worry about it too much.

Happy that you got it working and enjoy your new clock ;)
