### ISSUE TITLE
Dynamic config

### ISSUE THREAD

**Issue by Dusudest** [florianL21/LED-ClockShelf#9]
Hello, thank you for your project.
I flashed and tested version 1, it works fine with Blynk local server.
I flashed the dynamic-config version but I do not have access to the webUI page and I do not have access to my Blynk local server. 

Thank you for your help.

John.

**Comment by florianL21** [comment]
The dynamic config is jot really finished yet and is under active development. That being said, I do have this running on my clock without any major issues. Just note that only the Wifi and the blynk auth token settings in the web UI actually do something at the moment
